pool:
  vmImage: 'Linux Preview'
  
variables:
  buildConfiguration: 'Release'
  
resources:
- repo: self
  clean: true

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

    projects: '**/*.csproj'


- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'https://sonarcloud.io/dashboard?id=ChandramohanG_DevOpsDemo'

    organization: 'chandramohang-github'

    projectKey: 'ChandramohanG_DevOpsDemo'

    projectName: DevOpsDemo

- task: MSBuild@1
  displayName: 'Build solution aspnetcore.sln'
  inputs:
    solution: aspnetcore.sln

    msbuildArchitecture: x64

    clean: true


- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'


- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: ACR

    azureContainerRegistry: '{"loginServer":"cloudcontainerregistry.azurecr.io", "id" : "/subscriptions/6bff6c5c-be29-427b-a26d-dbecde768418/resourceGroups/Meetup_RG/providers/Microsoft.ContainerRegistry/registries/cloudcontainerregistry"}'

    dockerFile: dockerfile

    imageName: 'cloudcontainerregistry/aspnetcoredocker:$(Build.BuildId)'

    includeLatestTag: true

    enforceDockerNamingConvention: false


- task: Docker@0
  displayName: 'Push to ACR'
  inputs:
    azureSubscription: ACR

    azureContainerRegistry: '{"loginServer":"cloudcontainerregistry.azurecr.io", "id" : "/subscriptions/6bff6c5c-be29-427b-a26d-dbecde768418/resourceGroups/Meetup_RG/providers/Microsoft.ContainerRegistry/registries/cloudcontainerregistry"}'

    action: 'Run a Docker command'

    customCommand: 'push cloudcontainerregistry.azurecr.io/cloudcontainerregistry/aspnetcoredocker:latest'

    enforceDockerNamingConvention: false

  enabled: false


